# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "quanta-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "quanta-cli"
path = "src/main.rs"

[dependencies]
quanta-lexer = { path = "../quanta-lexer" }
quanta-ast = { path = "../quanta-ast" }
quanta-parser = { path = "../quanta-parser" }
quanta-typeck = { path = "../quanta-typeck" }
quanta-codegen = { path = "../quanta-codegen" }
quanta-emit = { path = "../quanta-emit" }
