# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[net]
git-fetch-with-cli = true

[source."git+https://github.com/Quantova/Q-Crypto.git?tag=v0.1.0"]
git = "https://github.com/Quantova/Q-Crypto.git"
tag = "v0.1.0"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
