# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "quanta-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
quanta-lexer = { path = "../quanta-lexer" }
quanta-ast = { path = "../quanta-ast" }
qtv-vm = { git = "https://github.com/Quantova/QVM.git", rev = "0026c817d09da828b458d2d82b89ae1c7afc151c" }

[dev-dependencies]
quanta-parser = { path = "../quanta-parser" }
quanta-typeck = { path = "../quanta-typeck" }
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "cf5ec8f2e884a7dda052fe04f38ef6a0c1dbd055" }
