# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "quanta-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
quanta-lexer = { path = "../quanta-lexer" }
quanta-ast = { path = "../quanta-ast" }
qtv-vm = { git = "https://github.com/Quantova/QVM.git", rev = "faf4870915c3419fa5e350e3257bfffd1074fe1f" }

[dev-dependencies]
quanta-parser = { path = "../quanta-parser" }
quanta-typeck = { path = "../quanta-typeck" }
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "4abe71e9fa84a6e670e6d5736d7533c3fd10a3ed" }
