# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "quanta-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
quanta-lexer = { path = "../quanta-lexer" }
quanta-ast = { path = "../quanta-ast" }
qtv-vm = { git = "https://github.com/Quantova/QVM.git", rev = "36329536940a917669e356535a459dbdf4db2463" }

[dev-dependencies]
quanta-parser = { path = "../quanta-parser" }
quanta-typeck = { path = "../quanta-typeck" }
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "33c7e9395ad23f07019909470d319211213e904f" }
